### ISSUE TITLE
change the extension icon to reflect whether [insert everywhere mode] is toggled on or off?

### ISSUE THREAD

**Issue by codemonkey-uk** [codemonkey-uk/local_time#11]
Sorry to re-open this, is it possible for you to change the extension icon to reflect whether it is toggled on or off? Maybe like a grey icon to show that it is off and normal icon to show it is on?

Also, I can see that the extension in the Firefox addon store is updated, but Chrome hasn't updated yet. Just wondering if the update is just taking a bit longer to show up in Chrome store?

_Originally posted by @chaoscreater in https://github.com/codemonkey-uk/local_time/issues/8#issuecomment-983057716_

**Comment by codemonkey-uk** [comment]
wip in status_icon branch, now workign through this, it is apparent that the plug in doesnt exactly have a simple "on/off" status

at any given time it can be in one of these states:

- "Unresponsive";
- "On Everywhere";
- "On Temporarily";
- "On for Selected Text";
- "Off";

"Unresponsive" can be temporary, and usually resolves itself automatically. Usually its very brief, sometimes it needs a page reload (like when the add on is updated while the tab is open).

I have tool-tips changing for these states working. What icon changes would you suggest @chaoscreater

**Comment by chaoscreater** [comment]
I think the main icon changes that I'd like to see are "On Temporarily" and "Off". 
99% of the time, my use case would be to temporarily toggle the addon ON and look at the converted times in some graphs shown in Azure, then toggle the addon off.

It just needs to be something simple to reflect the addon status, kinda like how Ublock or Greasemonkey does it. If they are enabled, it'll show show the normal icon and if disabled, it'll be greyed out.

![image](https://user-images.githubusercontent.com/18227319/144313592-b76141ab-766c-419b-9f68-af98e3afe858.png)

![image](https://user-images.githubusercontent.com/18227319/144313558-399c6bf9-802d-47ca-8d5c-088962dc544c.png)

**Comment by codemonkey-uk** [comment]
Could you try this, let me know what you think.

[local_time_0_4_7.zip](https://github.com/codemonkey-uk/local_time/files/7637618/local_time_0_4_7.zip)

**Comment by chaoscreater** [comment]
Thanks for the update! It works, but the icon seems rather hard to read in the toolbar. I can see the images in the folder and if open them in an image viewer, they look fine. But on the toolbar itself, it's a bit hard to see that it is "On Temporarily":

![image](https://user-images.githubusercontent.com/18227319/144330631-2c1cf895-0b18-4181-b318-4292ddb093ce.png)

**Comment by codemonkey-uk** [comment]
Try this: https://github.com/codemonkey-uk/local_time/files/7637749/local_time_0_5.zip

**Comment by chaoscreater** [comment]
Yup looks good! Thank you!
