### ISSUE TITLE
Feature Request - option to convert timezone for specific URLs or convert when enabled in extension setting?

### ISSUE THREAD

**Issue by chaoscreater** [codemonkey-uk/local_time#8]
Hi there,

I came across your extension and it is awesome! I do have one feature request if that's OK. 

I use Microsoft Azure and there are resource graphs that you can view. Some graphs show in UTC, some graphs show in local time (don't ask me why, it's just typical Microsoft). The times displayed in the graph cannot be selected, so the only way I can use your extension is to enable the setting - "Insert timezone conversions everywhere". However, I don't necessarily want this to apply to every page that I browse. I don't necessarily want the setting to apply to all of Azure either. 

Ideally, I'd like to just enable conversion (toggle on/off) from within the extension setting itself. Is that possible?

**Comment by codemonkey-uk** [comment]
Hi. I'm not sure I understand the request.

Where would you want to see the toggle? 

You say "from within the extension setting itself" - but that option is in the extensions settings.

What did you mean?

**Comment by chaoscreater** [comment]
OK, let me try to explain this.

Your extension will convert the timezones for a selected text, OR for everything on a webpage:

![image](https://user-images.githubusercontent.com/18227319/143788460-e433759c-f59c-46d5-b1c8-1bca82334dce.png)

Ideally, I'd like to convert the timezones based on the text I've selected. However, this is not always possible. In the screenshot below, I cannot select the text. It's a tooltip that changes when I move the mouse and the tooltip only shows when I hover the mouse on the graph:

![image](https://user-images.githubusercontent.com/18227319/143788533-87d1ec39-e480-45fb-a235-4e5a37ab6933.png)

This means that I need to go with the setting "Insert timezone conversions everywhere". But I don't want that, because not all times shown on all webpages need to be converted. They may already be displaying in the correct local time. It's only certain webpages or certain elements / parts of the webpage that need to be converted.

A quick and easy way to address this issue is to make the setting "Insert timezone conversions everywhere" as a toggle, WITHOUT going into the Extension settings. For example, UBlock does this well:

![image](https://user-images.githubusercontent.com/18227319/143788629-d3aac118-c56b-4cd6-9aec-1984f92ce192.png)

**Comment by codemonkey-uk** [comment]
Ah I see. The add on has an icon on the toolbar. I'll have a look see if I can support that or something like it. :)

**Comment by chaoscreater** [comment]
Yup there's an icon in the toolbar, but there isn't a way to quickly click on it to toggle on/off. I would greatly appreciate it if you could make this possible!

**Comment by codemonkey-uk** [comment]
Note for later: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Add_a_button_to_the_toolbar

**Comment by codemonkey-uk** [comment]
Hi,

I've made a fairly straightforward change that I hope will solve your problem. Are you able to test without me updating to the store? I've attached a zip file with a build of the update.

Its in a branch: browser-action

It would be super useful if you can confirm if this works for you before i upload to the store. :)

[local_time_0_4_4.zip](https://github.com/codemonkey-uk/local_time/files/7621218/local_time_0_4_4.zip)

**Comment by chaoscreater** [comment]
@codemonkey-uk - thanks for the update. I presume it is for Chrome/Edge? I've tried to add it and I'm getting this error:

`ErrorCould not load background script 'background.js`

**Comment by codemonkey-uk** [comment]
*facepalm*

thanks - try this:

[local_time_0_4_5.zip](https://github.com/codemonkey-uk/local_time/files/7621353/local_time_0_4_5.zip)

**Comment by chaoscreater** [comment]
OK, I've just tested and it's not doing anything. I'm testing this in Edge.

When I click on the old extension in the toolbar, I get these options:

![image](https://user-images.githubusercontent.com/18227319/143949763-e82e20fb-b6bf-4b5d-bf92-a9df1139e679.png)

When I click on the new version, it doesn't do anything. I can still go into the extension settings via another method, but clicking on it doesn't actually do anything.

**Comment by codemonkey-uk** [comment]
if you click it with a time on the page, it doesnt change the content on the page? 
its not going to pop up a menu / info box, its going to change the text on the page. Look where the time is displayed...

**Comment by codemonkey-uk** [comment]
In firefox you can load it via `about:debugging` → Load Temporary Add on...

Which is working for me.

**Comment by codemonkey-uk** [comment]
> I really just need a way to quickly toggle that highlighted setting on/off from the extension toolbar.

That is almost exactly what the change does (or rather, should do). When you click the button it (should) add any time zone conversions it finds that it did already do. Its supposed to be a way of getting the "conversions everywhere" feature "on demand". 

I dont know why its not working on Edge. Can you access the javascript console and see if there are any errors logged?

Try: `chrome://extensions/` → "Details" → Inspect Views: "background page"

**Comment by chaoscreater** [comment]
Oh cool, didn't know that. Got it loaded in Firefox and it is able to convert the time from your previous comment. I just checked in Edge and it is able to do that now as well (not sure why it couldn't before).

However, the problem is that not all webpages display the times directly. Sometimes, you can only see them in tooltips or mouse-over on graphs, like this:

![image](https://user-images.githubusercontent.com/18227319/143952997-dbe8fb27-51a3-4d19-8483-6c044ef137bd.png)

If I turn on the setting "Insert timezone conversion everywhere", then the tooltips in the graphs will be converted and that's great. But clicking on the extension in the toolbar doesn't convert the times for me, unless the time is directly on a webpage. Hope that makes sense.

**Comment by codemonkey-uk** [comment]
Ah! Of course! I see. Okay. Lets see if I can figure that out that...

**Comment by codemonkey-uk** [comment]
Try this:

[local_time_0_4_6.zip](https://github.com/codemonkey-uk/local_time/files/7621625/local_time_0_4_6.zip)

If that doesnt do it, can you share a link to a page that I can access to test against?

**Comment by chaoscreater** [comment]
It works! You bloody legend!

**Comment by codemonkey-uk** [comment]
Ace. I'll update the official plug in sites with 0_4_6 but it can take ages to get stuff approved so you'll probably want to keep using the version from this thread for now.

Rating / reviewing the add on on the chrome store is probably the best way to say thank you as a user. :D

**Comment by chaoscreater** [comment]
Awesome, I'll definitely rate & review for sure!

**Comment by chaoscreater** [comment]
Sorry to re-open this, is it possible for you to change the extension icon to reflect whether it is toggled on or off? Maybe like a grey icon to show that it is off and normal icon to show it is on?

Also, I can see that the extension in the Firefox addon store is updated, but Chrome hasn't updated yet. Just wondering if the update is just taking a bit longer to show up in Chrome store?

**Comment by codemonkey-uk** [comment]
I’ve created a new issue for icon status indicator. Chrome approvals can take ages, it could be 2 weeks!
